name: test
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: windows-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: node -v
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Npm install
        run: npm install
      - name: Run Tests
        run: npm run test
