name: test
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: windows-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: node -v
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Npm install
        run: npm install
      - name: Npm install react
        run: |
            cd react-app/
            npm install
      - name: Build react app
        run: |
           cd react-app/
           npm run build
      - name: Start react app
        run: |
           cd react-app/
           npm run start &
        shell: bash
      - name: Npm install angular
        run: |
            cd angular-app/
            npm install
      - name: Build angular app
        run: |
           cd angular-app/
           npm run build
      - name: Start angular app
        run: |
           cd angular-app/
           npm run start &
        shell: bash
      - name: Run Tests
        run: npm run test
